version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:4.2'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:3'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:2'
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
